//! Pins the OpenPGP key version produced by the production identity generator.
//!
//! Background: sequoia-openpgp 2.x added RFC 9580 ("v6") key support behind a
//! `Profile` type. v4 (RFC 4880) is 2.4.x's default, and `Identity::generate`
//! now pins `Profile::RFC4880` explicitly — but a default is not a guarantee and
//! an explicit pin can be dropped in a refactor. Every identity GitCellar has
//! ever stored is v4, and the fingerprint format differs between v4 and v6, so a
//! silent flip to v6 would break interop with existing stored certs, existing
//! key grants, and the machine-ID derivation that hashes the fingerprint.
//!
//! This test therefore asserts the *observable output* of the real production
//! path (`Identity::generate`), not the builder configuration — so it catches a
//! flip whether it comes from an upstream default change, a dropped
//! `.set_profile()` call, or a rewrite of the generator.
//!
//! Added during the sequoia-openpgp 1.x -> 2.x migration as one of its
//! verify-at-migration invariants.

use passkey_core::Identity;

/// The primary key and every subkey generated by the production identity
/// generator must be OpenPGP version 4.
#[test]
fn identity_generates_v4_keys() {
    let identity = Identity::generate("v4-pin-test@example.com")
        .expect("production identity generator should succeed");

    let cert = identity.cert();

    let primary_version = cert.primary_key().key().version();
    assert_eq!(
        primary_version, 4,
        "primary key must be OpenPGP v4 (RFC 4880), got v{primary_version}; \
         a v6 (RFC 9580) primary changes the fingerprint format and breaks \
         interop with every already-stored GitCellar identity"
    );

    // The three subkeys the generator adds (signing / transport encryption /
    // storage encryption) must match the primary's version — a mixed-version
    // cert is malformed for our purposes even if it parses.
    let mut subkey_count = 0;
    for ka in cert.keys().subkeys() {
        let version = ka.key().version();
        assert_eq!(
            version, 4,
            "subkey {} must be OpenPGP v4, got v{version}",
            ka.key().fingerprint()
        );
        subkey_count += 1;
    }

    assert_eq!(
        subkey_count, 3,
        "generator is expected to add exactly 3 subkeys (signing, transport \
         encryption, storage encryption); got {subkey_count}"
    );
}

/// A v4 Curve25519 fingerprint is 20 bytes / 40 hex chars. v6 fingerprints are
/// 32 bytes / 64 hex chars, so this is an independent second signal on the same
/// invariant that does not go through `version()`.
#[test]
fn identity_fingerprint_is_v4_shaped() {
    let identity = Identity::generate("v4-fpr-test@example.com")
        .expect("production identity generator should succeed");

    let hex = identity.cert().fingerprint().to_hex();
    assert_eq!(
        hex.len(),
        40,
        "expected a 40-hex-char v4 fingerprint, got {} chars ({hex}) — a \
         64-char fingerprint means the cert is v6 (RFC 9580)",
        hex.len()
    );
}
